Bring back new extensions (Workflows & Sidebar) from fork
neo4j-labs/neodash pull request #452
Opened 2023-05-23 15:01 UTC by nielsdejong

2023-06-01 12:28 UTC, BennuFire requested changes

2023-06-01 12:28 UTC, BennuFire commented on src/extensions/ExtensionConfig.tsx
Shouldn't the links point to 2.3?

2023-06-01 12:28 UTC, BennuFire commented on src/dashboard/DashboardThunks.ts
Add this into the migration to 2.3.

2023-06-04 12:56 UTC, nielsdejong commented on public/config.json
> +  "ssoEnabled": true,
at first I thought yes, but in hindsight it always needs a redirect URL to be set from the SSO provider.
So agree that false is better here.

2023-06-04 12:57 UTC, nielsdejong commented on package.json
> +    "@nivo/scatterplot": "^0.83.0",
Yes good idea, but i'll leave that for another issue in case stuff breaks :)

2023-06-04 12:57 UTC, nielsdejong commented on package.json
> +    "@nivo/scatterplot": "^0.83.0",
Made an issue here: https://github.com/neo4j-labs/neodash/issues/466

2023-06-04 12:58 UTC, nielsdejong commented on .github/workflows/master-deployment.yml
> +  - name: Set up Docker Buildx
Yes, will fix

2023-06-04 13:01 UTC, nielsdejong commented on .github/workflows/master-deployment.yml
> +    strategy:
nice catch, is a merge issue i think. let me fix it

2023-06-04 14:52 UTC, nielsdejong commented on src/card/settings/CardSettingsFooter.tsx
yeah this doesn't really make much sense.
I think it's something we always had and never fixed, because we never properly made the extensions un-hardcoded in the pro version of the app. 

With the new extension architecture idea that @alfredorubin96 is working on, we can probably break out the dependency here. Lets look at that in a new release after 2.3.0

2023-06-04 14:54 UTC, nielsdejong commented on src/extensions/ExtensionConfig.tsx
Fixed

2023-06-04 15:08 UTC, nielsdejong commented on src/dashboard/DashboardThunks.ts
Fixed!

2023-06-04 15:50 UTC, merged