Parameter support on natural language queries
neo4j-labs/neodash pull request #514
Opened 2023-07-13 12:45 UTC by BennuFire

2023-07-13 14:43 UTC, AleSim94 approved these changes

2023-07-14 06:54 UTC, nielsdejong commented on src/extensions/query-translator/clients/OpenAi/OpenAiClient.ts
> +  Remember to respect the schema and remove any unnecessary comments or explanations from your result. Remember that every $ prefixed word is a parameter.`;
I guess this is only to remind the LLM that we keep parameters in the Query. But we don't actually pass the real values for security reasons

2023-07-25 14:01 UTC, nielsdejong requested changes
Add some details to the docs pls

2023-07-26 10:28 UTC, nielsdejong approved these changes

2023-07-26 10:28 UTC, merged