Azure Open AI V1
neo4j-labs/neodash pull request #515
Opened 2023-07-13 13:04 UTC by BennuFire

2023-07-25 15:19 UTC, alfredorubin96 approved these changes

2023-07-29 08:04 UTC, nielsdejong commented on src/extensions/query-translator/state/QueryTranslatorThunks.ts
> +      console.log(tmpClient);
to remove

2023-07-29 08:06 UTC, nielsdejong commented on src/extensions/query-translator/QueryTranslatorConfig.ts
> +          label: 'AzureOpenAI EndPoint',
'Azure OpenAI Endpoint'

2023-07-29 08:07 UTC, nielsdejong commented on src/extensions/query-translator/QueryTranslatorConfig.ts
> +          label: 'AzureOpenAI API Key / Subscription Key',
Maybe just 'Subscription Key'?

2023-07-29 08:08 UTC, nielsdejong requested changes
Some suggestions

2023-07-31 07:11 UTC, BennuFire commented on src/extensions/query-translator/state/QueryTranslatorThunks.ts
> +      console.log(tmpClient);
Done

2023-07-31 07:12 UTC, BennuFire commented on src/extensions/query-translator/QueryTranslatorConfig.ts
> +          label: 'AzureOpenAI API Key / Subscription Key',
Done

2023-07-31 09:38 UTC, nielsdejong approved these changes

2023-07-31 09:38 UTC, merged