SSO multiple providers
neo4j-labs/neodash pull request #624
Opened 2023-09-18 08:59 UTC by BennuFire

2023-09-21 15:39 UTC, nielsdejong approved these changes

2023-09-21 15:41 UTC, nielsdejong commented on src/application/ApplicationThunks.ts
> +    dispatch(setSSOProviders(config.ssoProviders));
should we call this even if the list is `[]`?
Wouldn't that make this break for users that do not want to manually specify their providers?

2023-09-21 15:41 UTC, nielsdejong requested changes
See comment

2023-09-21 20:48 UTC, BennuFire commented
If the list is empty, all the providers will be valid.

El jue, 21 de sept de 2023, 17:41, Niels de Jong ***@***.***>
escribió:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/application/ApplicationThunks.ts
> <https://github.com/neo4j-labs/neodash/pull/624#discussion_r1333273776>:
>
> > @@ -377,6 +379,7 @@ export const loadApplicationConfigThunk = () => async (dispatch: any, getState:
>      }
>      const state = getState();
>      dispatch(setSSOEnabled(config.ssoEnabled, state.application.cachedSSODiscoveryUrl));
> +    dispatch(setSSOProviders(config.ssoProviders));
>
> should we call this even if the list is []?
> Wouldn't that make this break for users that do not want to manually
> specify their providers?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/neo4j-labs/neodash/pull/624#pullrequestreview-1638184055>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABYOAI5ORABLKGCGXU66PGLX3RN25ANCNFSM6AAAAAA44MBYK4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-09-22 12:33 UTC, nielsdejong approved these changes

2023-09-22 12:34 UTC, merged